### ISSUE TITLE
How to use your code for my own task?

### ISSUE THREAD

**Issue by certic1** [ZZY-Zhou/RENet#12]
Thank you for your work.Now i want to use your method to achieve foreign object detection on power lines.When running training.py it needs DSEC-GT.pkl. If i use my own dataset,how can i generate pkl file like DSEC-GT.pkl and what else needs to be done?

**Comment by Ollie-olivia** [comment]
> Thank you for your work.Now i want to use your method to achieve foreign object detection on power lines.When running training.py it needs DSEC-GT.pkl. If i use my own dataset,how can i generate pkl file like DSEC-GT.pkl and what else needs to be done?感谢你的工作。现在我想用你的方法来实现电力线路上的异物检测。运行 training.py 时需要 DSEC-GT.pkl。如果我使用自己的数据集，如何生成像 DSEC-GT.pkl 这样的 pkl 文件？还需要做些什么？

同问，请问您最后解决了吗
