### ISSUE TITLE
How to use visual parts of the code？

### ISSUE THREAD

**Issue by Brandon985** [ZZY-Zhou/RENet#14]
Hello, thank you very much for your excellent work, I want to generate a similar diagram in the paper when implementing the code, but some modules are missing, can you tell me what to do?
<img width="719" alt="2024-04-05_214205" src="https://github.com/ZZY-Zhou/RENet/assets/88612009/1964c10a-27c9-47bc-8099-2ddea3047922">

**Comment by FabriceQwQ** [comment]
Hi, did you figure out how to use this part of code, and successfully getting the visiual result?
