### ISSUE TITLE
Provided Dataset cannot direct to train?

### ISSUE THREAD

**Issue by tlwzzy** [ZZY-Zhou/RENet#3]
Hi, thanks for the great work and dataset first.

for the dataset download by the google drive you provides, I can get

└── DSEC_MOD
    ├── training
    │   ├── zurich_city_00_a
    │   │   ├── gt_bb
    │   │   │   ├── 000000.txt
    │   │   │   └── ...
    │   │   ├── rgb_calib
    │   │   │   ├── 000000.png
    │   │   │   └── ...
    │   │   └── events  
    │   │       └── left
    │   │           ├── events.h5
    │   │           └── rectify_map.h5
    │   └── ...
    └── testing
        ├── zurich_city_13_a
        │   └── ...
        └── ... 

but from the dataset define, It seems the training data structure should be /data/DSEC_MOD/RGB-images,... etc
```python
    def imagefile(self, v, i):
        return os.path.join(self.ROOT_DATASET_PATH, 'RGB-images', v, '{:0>6}.png'.format(i))

    def eventfile(self, v, i):
        return os.path.join(self.ROOT_DATASET_PATH, 'Event-images', v, '{:0>6}.png'.format(i))

    def eventfile_30ms(self, v, i):
        return os.path.join(self.ROOT_DATASET_PATH, 'Event-images_30ms', v, '{:0>6}.png'.format(i))
    def eventfile_50ms(self, v, i):
        return os.path.join(self.ROOT_DATASET_PATH, 'Event-images_50ms', v, '{:0>6}.png'.format(i))
```

so how to convert the downloaded traindataset and testdataset to the form that can directly trained by the method in paper?

Anyway, Thanks a lot.

**Comment by ZZY-Zhou** [comment]
Hello,

The format of DSEC-MOD is designed more for a general usage, including but not limited to customised event temporal scales, for instance.
Details can be found in *Section III-A. E-TMA: Event-based Temporal Multi-scale Aggregation* in our [paper](https://arxiv.org/abs/2209.08323).

If you would like to get the same results in our paper, the generated event frames we used can be downloaded [here](https://github.com/ZZY-Zhou/RENet/blob/main/README.md#pre-trained-weights).

Hope could help.

**Comment by tlwzzy** [comment]
> Hello,
> 
> The format of DSEC-MOD is designed more for a general usage, including but not limited to customised event temporal scales, for instance. Details can be found in _Section III-A. E-TMA: Event-based Temporal Multi-scale Aggregation_ in our [paper](https://arxiv.org/abs/2209.08323).
> 
> If you would like to get the same results in our paper, the generated event frames we used can be downloaded [here](https://github.com/ZZY-Zhou/RENet/blob/main/README.md#pre-trained-weights).
> 
> Hope could help.

Thanks for answer. So just download the Preprocessed Event images and rename, with RGB-Images rename can train to reproduce the results in paper? I'll try to run this code.

Anyway, thanks for help and the great work.

**Comment by tlwzzy** [comment]
> Hello,
> 
> The format of DSEC-MOD is designed more for a general usage, including but not limited to customised event temporal scales, for instance. Details can be found in _Section III-A. E-TMA: Event-based Temporal Multi-scale Aggregation_ in our [paper](https://arxiv.org/abs/2209.08323).
> 
> If you would like to get the same results in our paper, the generated event frames we used can be downloaded [here](https://github.com/ZZY-Zhou/RENet/blob/main/README.md#pre-trained-weights).
> 
> Hope could help.

HI, Here's another question, where can I found the code that process the raw events to the 15ms/30ms/50ms images that provided? Any clue?

**Comment by ZZY-Zhou** [comment]
Hello,
We applied traditional method to generate frame-like event representation, basic code can be found in the repository of [parent dataset DSEC](https://github.com/ZZY-Zhou/RENet#parent-dataset-dsec).
If you may be interested in other possible methods, details can be found in the section of ablation study in our [paper](https://arxiv.org/abs/2209.08323).

**Comment by wwgjob** [comment]
> Hi, thanks for the great work and dataset first.
> 
> for the dataset download by the google drive you provides, I can get
> 
> └── DSEC_MOD ├── training │ ├── zurich_city_00_a │ │ ├── gt_bb │ │ │ ├── 000000.txt │ │ │ └── ... │ │ ├── rgb_calib │ │ │ ├── 000000.png │ │ │ └── ... │ │ └── events │ │ └── left │ │ ├── events.h5 │ │ └── rectify_map.h5 │ └── ... └── testing ├── zurich_city_13_a │ └── ... └── ...
> 
> but from the dataset define, It seems the training data structure should be /data/DSEC_MOD/RGB-images,... etc
> 
> ```python
>     def imagefile(self, v, i):
>         return os.path.join(self.ROOT_DATASET_PATH, 'RGB-images', v, '{:0>6}.png'.format(i))
> 
>     def eventfile(self, v, i):
>         return os.path.join(self.ROOT_DATASET_PATH, 'Event-images', v, '{:0>6}.png'.format(i))
> 
>     def eventfile_30ms(self, v, i):
>         return os.path.join(self.ROOT_DATASET_PATH, 'Event-images_30ms', v, '{:0>6}.png'.format(i))
>     def eventfile_50ms(self, v, i):
>         return os.path.join(self.ROOT_DATASET_PATH, 'Event-images_50ms', v, '{:0>6}.png'.format(i))
> ```
> 
> so how to convert the downloaded traindataset and testdataset to the form that can directly trained by the method in paper?
> 
> Anyway, Thanks a lot.

Hello,

I would like to ask if you were able to successfully retrain the model in the end? Because I am currently working on conducting experiments for this paper as well. Could you please share your experience with this paper?

I sincerely appreciate your assistance and help.

Thank you very much.

I can read Chinese.

**Comment by Zongwei97** [comment]
Please refer to https://github.com/ZZY-Zhou/RENet/issues/4#issuecomment-1680544849

**Comment by qiaobendong** [comment]
你好，请问你成功对数据集训练了 吗？谢谢

**Comment by xqdd333** [comment]
basic code can be found in the repository of [parent dataset DSEC](https://github.com/ZZY-Zhou/RENet#parent-dataset-dsec)
Did you find the generated code?
