### ISSUE TITLE
when unrar the dataset, replace the events.h5 file? 

### ISSUE THREAD

**Issue by emilyemliyM** [ZZY-Zhou/RENet#9]
Hi, I just download the data files, and unrar these. like the command: unrar e -r DSEC_MOD_testing.rar DSEC_Test/
But I met a problem.

![image](https://github.com/ZZY-Zhou/RENet/assets/88700988/01d1cb97-2823-4f5e-9264-e1369020193e)

So I need to replace it ?

**Comment by ZZY-Zhou** [comment]
Hello,

Thank you for your interest in our work.

Sorry for the late reply.
No you do not need to replace the .h5 or other files; instead, the `unrar` command need to be modified.

Please notice that `unrar x <myfile>` preserves directory structure in archive, while `unrar e <myfile>` flattens it.

Hope could help.
